"""
module to train a PINN
to solve an ODE or systme of ODEs
"""

import torch
import torch.nn as nn
from typing import List, Callable
import copy
from .derivatives import derivatives
from .pinn import PINN
from .training import train


def factorials_up_to_n(n :int) -> torch.Tensor:
    """
    returns a tensor of factorials
    from 0! to n!
    """
    if n < 0:
        raise ValueError("Factorials only have non-negative arguments")
    facs = torch.ones(n + 1, dtype=torch.float32)
    for k in range(1, n + 1):
        facs[k] = facs[k-1] * k
    return facs

def taylor_polynomial(a: float, ics: List[float]) -> Callable[[torch.Tensor], torch.Tensor]:
    """
    Generate Taylor polynomial centered at a
    of degree len(ics) - 1 using the ics to get coefficients
    """
    n = len(ics)
    facs = factorials_up_to_n(n)
    first_ic = ics[0]
    n_vars = 1 if isinstance(first_ic, (int, float)) else len(first_ic)
    def g(x):
        # make x at least 1D for broadcasting
        x = x.unsqueeze(-1) if x.ndim == 1 else x  # shape [batch,1] if batched
        result = torch.zeros(x.shape[0], n_vars, dtype=torch.float32)  # shape [batch, n_vars]
        for k, yk in enumerate(ics):
            yk_tensor = yk.clone().detach().float() if isinstance(yk, torch.Tensor) else torch.tensor(yk, dtype=torch.float32)
            result += (x - a)**k * (yk_tensor / facs[k])  # broadcasts over batch
        return result.squeeze(0) if result.shape[0] == 1 else result  # handle scalar x
    return g

def get_y_trial(a: float, ics: list, NN: nn.Module) -> Callable[[torch.Tensor], torch.Tensor]:
    """
    given a point a as a center,
    a list y(a), y'(a),... y^(n)(a)
    create trial solution that is the taylor polynomial
    generated by the ICs + (x-a)^n * NN(x-a)
    """
    n = len(ics)
    # get the taylor polynomial based on the ICs
    poly = taylor_polynomial(a, ics)
    
    def y_trial(x):
        # make x 2D: [batch, 1] for NN
        x_in = x.unsqueeze(-1) if x.ndim == 1 else x
        return poly(x_in) + (x_in - a)**n * NN(x_in - a)
    
    return y_trial

def get_loss(a: float, ics: List[float], NN: nn.Module, F: Callable[..., torch.Tensor]) -> Callable[[torch.Tensor], torch.Tensor]:
    """
    generating the loss function 
    based on F(x,y,y',...y^n) = 0
    """
    y_trial_fn = get_y_trial(a, ics, NN)
    def loss(x):
        y0 = y_trial_fn(x)
        derivs = derivatives(y0, x, len(ics))
        residual = F(x, *derivs)
        return torch.mean(residual**2)
    
    return loss



def ode_solve(
        F : Callable[..., torch.Tensor],
        a : float,
        ics : List[float | torch.Tensor],
        X : torch.Tensor,
        NN : PINN,
        return_checkpoints : bool = False,
        **train_args : dict
) -> Callable | tuple[Callable, list]:
    """
    Wrapper to call solve for an ODE
    Parameters
    ----------
    F : Callable
        F(x,y,y',...) which is the DE
    a: float
        x0 for ics
    ics: List [float or Tensor]
        list of y0, y_prime0, ...
    X : torch.Tensor or list[torch.Tensor]
        training data
    NN: PINN
        PINN to train to solve the DE
    return_checkpoints : bool
        whether or not to return intermediate solutions
    **train_args: dict
        other arguments that can be passed directly to train
    
    Returns
    -------
    solution: Callable
        the solution to the ODE that's y_trial(a, ics, NN)
    checkpoints (optional) : List[ tuple(int, callable) ]
        when return_checkpoints is true, a list
        of pairs (epoch, trial) where trial is intermediate
        solution at epoch
    """
    # make sure that X is two dimensional
    X = X.unsqueeze(-1) if X.ndim == 1 else X
    # get the loss function
    loss_fn = get_loss(a, ics, NN, F)
    # Run the generic training loop
    result = train(
        NN=NN,
        X=X,
        loss_fn=loss_fn,
        return_checkpoints=return_checkpoints,
        use_grad=True,
        **train_args
    )

    # Wrap checkpoints so each stores only state_dict
    wrapped_checkpoints = None
    if return_checkpoints:
        checkpoints = result  # train returns the raw checkpoints
        wrapped_checkpoints = []
        for epoch, nn_checkpoint in checkpoints:
            # copy state_dict so we don't mutate the original network
            state = {k: v.clone() for k, v in nn_checkpoint.state_dict().items()}

            # closure capturing the state dict
            def trial(x, state=state):
                nn_copy = copy.deepcopy(NN)  # fresh network of same architecture
                nn_copy.load_state_dict(state)
                nn_copy.eval()
                return get_y_trial(a, ics, nn_copy)(x)

            wrapped_checkpoints.append((epoch, trial))

    solution = get_y_trial(a, ics, NN)
    if return_checkpoints:
        assert wrapped_checkpoints is not None
        return solution, wrapped_checkpoints
    return solution
